import { AGENT_NAMES } from "../domain/agent.js";
import { ACTION_NAMES } from "../domain/action.js";

/**
 * Canonical JSONC renderers for the user-level configuration files.
 *
 * Ownership is split deliberately:
 *
 * ```text
 * values    user-owned    preserved verbatim across reinstall
 * comments  maintainer-owned  regenerated from these templates
 * ```
 *
 * Regeneration is whole-file rather than line patching: the installer parses
 * the existing values, then re-renders the current canonical document around
 * them. That keeps comments truthful as the product changes, and makes the
 * outcome deterministic instead of dependent on how a file was previously
 * edited.
 *
 * Consequence, stated plainly: user-added comments are NOT preserved. Only
 * semantic values are. Formatting, key ordering and indentation are normalised
 * too.
 *
 * No template contains a credential, token or API-key field. Authentication is
 * provider-owned and Synaphex never stores it.
 */

/** Marks a file as maintainer-rendered, and lets tests detect a refresh. */
export const TEMPLATE_MARKER = "Synaphex-managed comments";

function header(title: string, lines: readonly string[]): string {
  return [
    `// ${title}`,
    `// ${TEMPLATE_MARKER}: this file's comments are regenerated by`,
    "// `synaphex install`. Your values are preserved; your comments are not.",
    "//",
    ...lines.map((line) => (line.length === 0 ? "//" : `// ${line}`)),
  ].join("\n");
}

/** Stable two-space JSON with deterministic key order as given. */
function render(value: unknown, indent = 0): string {
  const pad = " ".repeat(indent);
  const inner = " ".repeat(indent + 2);
  if (Array.isArray(value)) {
    if (value.length === 0) {
      return "[]";
    }
    return `[\n${value
      .map((entry) => `${inner}${render(entry, indent + 2)}`)
      .join(",\n")}\n${pad}]`;
  }
  if (value !== null && typeof value === "object") {
    const entries = Object.entries(value as Record<string, unknown>);
    if (entries.length === 0) {
      return "{}";
    }
    return `{\n${entries
      .map(([key, entry]) => `${inner}${JSON.stringify(key)}: ${render(entry, indent + 2)}`)
      .join(",\n")}\n${pad}}`;
  }
  return JSON.stringify(value);
}

export function renderAgentConfig(state: unknown): string {
  return `${header("Synaphex agent configuration", [
    "Each of the six agents is configured independently. An agent stays",
    '"unconfigured" until you give it a provider, a surface and a model.',
    "",
    "  provider   openai | anthropic | google",
    "  surface    cli",
    "  model      required for every configured agent; no default is invented",
    "  settings   optional provider-specific options; omit to use the",
    "             provider's own defaults",
    "",
    "Execution surfaces in v0.1:",
    "  cli      supported",
    '  vscode   NOT supported -- a "vscode" target is refused before',
    "           execution rather than silently run through the CLI",
    "",
    "Provider targets in v0.1:",
    "  openai, anthropic   executable through their CLI runtimes",
    "  google              recognised, but execution is currently",
    "                      unavailable and fails closed",
    "",
    "Installing a provider MCP host does not configure any agent, and",
    "Synaphex never stores credentials -- authentication is provider-owned.",
    "",
    `Agents: ${AGENT_NAMES.join(", ")}`,
  ])}\n${render(state)}\n`;
}

export function renderAgentBehavior(state: unknown): string {
  return `${header("Synaphex agent behavior", [
    "`outputFields` lists the payload fields each agent is allowed to",
    "persist. A result carrying a field that is not listed here is rejected",
    "before any state is written, so narrowing this list narrows what an",
    "agent can record.",
    "",
    "Removing a field does not weaken any role contract: the contracts",
    "themselves are fixed in code and are not configurable.",
  ])}\n${render(state)}\n`;
}

export function renderRules(state: unknown): string {
  return `${header("Synaphex global rules", [
    "Rules decide whether one agent may call another, and whether a",
    "requested action may run.",
    "",
    `  decisions   allow | ask | deny`,
    `  actions     ${ACTION_NAMES.join(", ")}`,
    "",
    "Precedence, most specific first:",
    "",
    "  task  >  project  >  global  >  default deny",
    "",
    "Anything not matched by a rule is denied. `ask` requires an explicit",
    "one-time approval and never becomes a persistent grant.",
    "",
    "These rules cannot widen a role contract. A prohibition fixed in code",
    '-- PLANNER may not call CODER, for instance -- stays denied even if a',
    'rule here says "allow".',
    "",
    "Of the actions above, only `network` currently has an execution path;",
    "`git_push` and `ci` are classified but not executed in v0.1.",
  ])}\n${render(state)}\n`;
}
